#! /bin/bash

if [ $# -lt 4 ]; then
  echo "Usage: ... <username> <homedir> <shell:bash|zsh|fish> <pwd>"
  exit
fi

user=$1; home=$2; shell=$(command -v $3); cwd=$4; shift 4

id -u $user &> /dev/null
if [ $? -ne 0 ]; then
  groupadd -f wheel
  useradd -M -N -g wheel -d $home $user
  passwd -d $user &> /dev/null
fi

exec sudo -u $user -i exec $shell -c \
"
  [ -d $cwd  ] && cd $cwd;
  [ $# -gt 0 ] && exec $*;
  exec $shell;
"
